#!/bin/bash

file="/proc/bus/input/devices"
IFS=$'\n'

declare -A device_info
current_id=""

while read -r line
do
    if [[ $line =~ ^I: ]]; then
        if [[ -n "$current_id" ]]; then
            output=""
            output+="${device_info[I]:-N/A} "
            output+="${device_info[N]:-N/A} "
            echo "$output"
        fi
        current_id=$(echo "$line" | cut -c3-)
        device_info=() 
        device_info[I]="$current_id"
    else
        case $line in
            N:*) device_info[N]=$(echo "$line" | cut -c3-) ;;
        esac
    fi
done < "$file"

if [[ -n "$current_id" ]]; then
    output=""
    output+="${device_info[I]:-N/A} "
    output+="${device_info[N]:-N/A} "
    echo "$output"
fi
